'use client'

import { useMemo, useState } from 'react'
import { useReports, useGenerateReport, type SlaReportPayload } from '@/hooks/use-console-data'
import { EmptyState, TONE_COLOR, SectionHeader, StatusPill } from '@/components/console/primitives'
import { Skeleton } from '@/components/ui/skeleton'
import { toast } from 'sonner'
import { ArrowDownRight, ArrowUpRight, Check, FileBarChart, Download, Play, Gauge, Timer, ShieldCheck, Flame, GitCompareArrows, X } from 'lucide-react'
import { cn } from '@/lib/utils'
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from '@/components/ui/select'
import { Button } from '@/components/ui/button'

const SERVICES = [
  'api-gateway', 'checkout-service', 'auth-service', 'search-cluster',
  'billing-worker', 'edge-cdn', 'ingest-gateway',
]
const WINDOWS = [7, 14, 30, 90]
const SLO_PRESETS = [99, 99.5, 99.9, 99.95, 99.99]

/**
 * SLA reports, generated by the C# reporting plane (:4200). Everything the
 * view renders comes back from one POST: availability, error budget, burn
 * rate, per-day rollups and detected incident episodes.
 */
export function ReportsView() {
  const [service, setService] = useState('api-gateway')
  const [windowDays, setWindowDays] = useState(14)
  const [sloTarget, setSloTarget] = useState(99.9)
  const [lastReport, setLastReport] = useState<SlaReportPayload | null>(null)
  const [compareIds, setCompareIds] = useState<string[]>([])
  const [comparePair, setComparePair] = useState<[SlaReportPayload, SlaReportPayload] | null>(null)

  const reportsQuery = useReports('')
  const generate = useGenerateReport()

  const reports = reportsQuery.data?.reports ?? []
  const reportById = useMemo(() => new Map(reports.map((r) => [r.id, r])), [reports])

  const generateReport = () => {
    toast.promise(
      generate.mutateAsync(
        { serviceId: service, windowDays, sloTarget },
        { onSuccess: (r) => setLastReport(r) },
      ),
      {
        loading: `Computing ${windowDays}-day SLA for ${service}…`,
        success: (r) => `Report ready · ${r.summary.availabilityPct.toFixed(3)}% availability`,
        error: (e) => e.message,
      },
    )
  }

  const shown = lastReport ?? reports[0] ?? null

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-lg font-semibold tracking-tight">
            <FileBarChart className="h-4 w-4 text-primary" />
            SLA reports
          </h1>
          <p className="text-xs text-muted-foreground">
            availability · error budget · burn rate — computed by the C# reporting plane :4200
          </p>
        </div>
        <div
          className="rounded-full border px-2.5 py-1 text-[11px] text-muted-foreground"
          title="SLA reports are generated by the .NET code-tier service"
        >
          reporting plane · {reportsQuery.data ? `${reportsQuery.data.count} saved` : '…'}
        </div>
      </div>

      {/* Generator ------------------------------------------------------- */}
      <div className="card-surface p-4">
        <div className="flex flex-wrap items-end gap-3">
          <Field label="Service">
            <Select value={service} onValueChange={setService}>
              <SelectTrigger className="h-8 w-44 font-mono text-xs" aria-label="report service">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {SERVICES.map((s) => (
                  <SelectItem key={s} value={s} className="font-mono text-xs">{s}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </Field>

          <Field label="Window">
            <div className="flex gap-1">
              {WINDOWS.map((d) => (
                <button
                  key={d}
                  onClick={() => setWindowDays(d)}
                  aria-pressed={windowDays === d}
                  className={cn(
                    'h-8 rounded-md border px-2.5 text-xs transition-colors',
                    windowDays === d
                      ? 'border-primary/40 bg-primary/10 font-medium text-primary'
                      : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground',
                  )}
                >
                  {d}d
                </button>
              ))}
            </div>
          </Field>

          <Field label="SLO target">
            <div className="flex gap-1">
              {SLO_PRESETS.map((s) => (
                <button
                  key={s}
                  onClick={() => setSloTarget(s)}
                  aria-pressed={sloTarget === s}
                  className={cn(
                    'h-8 rounded-md border px-2.5 font-mono text-xs transition-colors',
                    sloTarget === s
                      ? 'border-primary/40 bg-primary/10 font-medium text-primary'
                      : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground',
                  )}
                >
                  {s}%
                </button>
              ))}
            </div>
          </Field>

          <Button
            size="sm"
            className="ml-auto h-8 gap-1.5 text-xs"
            disabled={generate.isPending}
            onClick={generateReport}
          >
            <Play className="h-3 w-3" />
            {generate.isPending ? 'Computing…' : 'Generate report'}
          </Button>
        </div>
        <p className="mt-3 text-[11px] text-muted-foreground">
          window: last {windowDays} days (UTC) · SLO {sloTarget}% → error budget{' '}
          {fmtBudget(windowDays, sloTarget)} · reports persist on the reporting plane and appear below
        </p>
      </div>

      {/* Active report ---------------------------------------------------- */}
      {reportsQuery.isLoading && !shown && <ReportSkeleton />}
      {!reportsQuery.isLoading && !shown && (
        <div className="card-surface">
          <EmptyState
            title="No SLA reports yet"
            hint="pick a service and window, then Generate report"
          />
        </div>
      )}
      {shown && <ReportDetail report={shown} />}

      {/* Compare ----------------------------------------------------------- */}
      {comparePair && <ReportCompare a={comparePair[0]} b={comparePair[1]} onClose={() => setComparePair(null)} />}

      {/* History ----------------------------------------------------------- */}
      {reports.length > 0 && (
        <div className="card-surface">
          <SectionHeader
            title="Saved reports"
            hint="persisted by reporting-core · newest first"
            right={
              <div className="flex items-center gap-2">
                {compareIds.length > 0 && (
                  <>
                    <span className="text-[11px] tabular text-muted-foreground">{compareIds.length}/2 selected</span>
                    <Button
                      size="sm"
                      className="h-7 gap-1.5 px-2.5 text-[11px]"
                      disabled={compareIds.length !== 2}
                      title={compareIds.length === 2 ? 'Render drift comparison' : 'pick one more report'}
                      onClick={() => {
                        const [a, b] = compareIds.map((id) => reportById.get(id)!)
                        if (a && b) {
                          setComparePair([a, b])
                          toast.success('Comparison ready', { description: `${a.serviceId} vs ${b.serviceId} — drift table below` })
                        }
                      }}
                    >
                      <GitCompareArrows className="h-3 w-3" />
                      Compare
                    </Button>
                    <button
                      onClick={() => setCompareIds([])}
                      className="flex h-7 items-center gap-1 rounded-md border px-2 text-[11px] text-muted-foreground transition-colors hover:border-ring hover:text-foreground"
                    >
                      <X className="h-3 w-3" /> clear
                    </button>
                  </>
                )}
                <span className="text-[11px] text-muted-foreground">
                  {reportsQuery.data?.count ?? reports.length} on file
                </span>
              </div>
            }
          />
          <div className="divide-y divide-border/50 border-t border-border/50">
            {reports.map((r) => {
              const selIdx = compareIds.indexOf(r.id)
              const selected = selIdx >= 0
              return (
                <div
                  key={r.id}
                  className={cn(
                    'flex w-full flex-wrap items-center gap-x-4 gap-y-1 px-4 py-2.5 text-left text-xs transition-colors hover:bg-accent/40',
                    shown?.id === r.id && 'bg-accent/60',
                    selected && 'bg-primary/5 ring-1 ring-inset ring-primary/40',
                  )}
                >
                  <button
                    aria-label={selected ? 'remove from comparison' : 'add to comparison'}
                    aria-pressed={selected}
                    title={selected ? 'remove from comparison' : 'compare (pick two)'}
                    onClick={() =>
                      setCompareIds((prev) =>
                        selected
                          ? prev.filter((id) => id !== r.id)
                          : prev.length >= 2
                            ? prev
                            : [...prev, r.id],
                      )
                    }
                    className={cn(
                      'flex h-4 w-4 shrink-0 items-center justify-center rounded border transition-colors',
                      selected ? 'border-primary bg-primary/20 text-primary' : 'border-muted-foreground/40 text-transparent hover:border-primary/60',
                    )}
                  >
                    <Check className="h-3 w-3" strokeWidth={3} />
                  </button>
                  {selected && (
                    <span className="flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-primary/20 font-mono text-[9px] font-bold text-primary">
                      {selIdx === 0 ? 'A' : 'B'}
                    </span>
                  )}
                  <button onClick={() => setLastReport(r)} className="flex min-w-0 flex-1 flex-wrap items-center gap-x-4 gap-y-1 text-left">
                    <span className="w-40 font-mono text-foreground/90">{r.serviceId}</span>
                    <span className="tabular text-muted-foreground">
                      {new Date(r.from).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })} →{' '}
                      {new Date(r.to).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })}
                    </span>
                    <span className="tabular">SLO {r.sloTarget}%</span>
                    <span
                      className="tabular font-medium"
                      style={{ color: availColor(r.summary.availabilityPct, r.sloTarget) }}
                    >
                      {r.summary.availabilityPct.toFixed(3)}%
                    </span>
                    <span className="tabular text-muted-foreground">
                      burn ×{r.summary.burnRate.toFixed(2)}
                    </span>
                    <span className="ml-auto tabular text-muted-foreground">
                      {r.incidents.length} incident{r.incidents.length === 1 ? '' : 's'}
                    </span>
                  </button>
                </div>
              )
            })}
          </div>
        </div>
      )}
    </div>
  )
}

// ---- report detail -----------------------------------------------------------

function ReportDetail({ report }: { report: SlaReportPayload }) {
  const s = report.summary
  const availTone = s.availabilityPct >= report.sloTarget ? 'ok' : s.burnRate >= 6 ? 'crit' : 'warn'
  const budgetTone =
    s.errorBudgetPctRemaining <= 0 ? 'crit' : s.errorBudgetPctRemaining < 25 ? 'warn' : 'ok'

  return (
    <div className="space-y-4">
      {/* headline tiles */}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <MetricTile
          icon={<Gauge className="h-3.5 w-3.5" />}
          label="Availability"
          value={`${s.availabilityPct.toFixed(3)}%`}
          sub={`target ${report.sloTarget}%`}
          color={TONE_COLOR[availTone as 'ok' | 'warn' | 'crit']}
        />
        <MetricTile
          icon={<ShieldCheck className="h-3.5 w-3.5" />}
          label="Error budget left"
          value={`${s.errorBudgetPctRemaining.toFixed(1)}%`}
          sub={`${s.errorBudgetMinutes.toFixed(1)} min allowed`}
          color={TONE_COLOR[budgetTone as 'ok' | 'warn' | 'crit']}
        />
        <MetricTile
          icon={<Flame className="h-3.5 w-3.5" />}
          label="Burn rate"
          value={`×${s.burnRate.toFixed(2)}`}
          sub={burnVerdict(s.burnRate)}
          color={s.burnRate >= 6 ? TONE_COLOR.crit : s.burnRate >= 1 ? TONE_COLOR.warn : TONE_COLOR.ok}
        />
        <MetricTile
          icon={<Timer className="h-3.5 w-3.5" />}
          label="Downtime"
          value={`${s.totalDowntime.toFixed(1)}m`}
          sub={`${fmtCompact(s.failedRequests)} failed / ${fmtCompact(s.totalRequests)} reqs`}
          color={TONE_COLOR.neutral}
        />
      </div>

      <div className="grid gap-4 xl:grid-cols-[1fr_380px]">
        {/* daily rollup strip */}
        <div className="card-surface">
          <SectionHeader
            title="Daily availability"
            hint={`${report.daily.length} UTC days · click a day for detail`}
            right={
              <a
                href={`/api/reports/${report.id}/export?format=csv`}
                download
                className="flex h-7 items-center gap-1.5 rounded-md border bg-card/60 px-2.5 text-[11px] text-muted-foreground transition-colors hover:border-ring hover:text-foreground"
              >
                <Download className="h-3 w-3" />
                CSV
              </a>
            }
          />
          <div className="px-4 pb-4">
            <div className="flex h-16 items-end gap-[2px]" role="img" aria-label="daily availability bars">
              {report.daily.map((d) => {
                const deficit = Math.max(0, 100 - d.uptimePct)
                // Visual scale: 0% deficit → full height, 1% deficit → 20%,
                // anything worse floors at 8%. Exact figures live in the tooltip.
                const h = deficit === 0 ? 100 : Math.max(8, 100 - deficit * 80)
                const met = d.uptimePct >= report.sloTarget
                return (
                  <div
                    key={d.date}
                    className="group relative flex h-full flex-1 items-end"
                    title={`${d.date} · ${d.uptimePct.toFixed(3)}% · ${fmtCompact(d.requests)} reqs · ${fmtCompact(d.errors)} errors`}
                  >
                    <div
                      className="w-full rounded-sm transition-all group-hover:opacity-100"
                      style={{
                        height: `${h}%`,
                        background: met ? 'var(--ok)' : deficit > 0.5 ? 'var(--crit)' : 'var(--warn)',
                        opacity: met ? 0.75 : 1,
                      }}
                    />
                  </div>
                )
              })}
            </div>
            <div className="mt-1.5 flex justify-between text-[10px] text-muted-foreground tabular">
              <span>{report.daily[0]?.date}</span>
              <span>{report.daily[report.daily.length - 1]?.date}</span>
            </div>
            <div className="mt-3 flex flex-wrap gap-4 text-[11px] text-muted-foreground">
              <LegendDot color="var(--ok)" label="SLO met" />
              <LegendDot color="var(--warn)" label="minor deficit" />
              <LegendDot color="var(--crit)" label=">0.5% down" />
            </div>
          </div>
        </div>

        {/* incidents in window */}
        <div className="card-surface">
          <SectionHeader
            title="Incidents in window"
            hint="episodes with hourly error rate ≥ 2%"
          />
          <div className="max-h-72 space-y-2 overflow-y-auto px-4 pb-4 scroll-thin">
            {report.incidents.length === 0 && (
              <div className="rounded-md border border-dashed border-ok/30 bg-ok/5 px-3 py-6 text-center text-xs text-ok">
                clean window — no error-rate episodes detected
              </div>
            )}
            {report.incidents.map((inc, i) => {
              const tone = inc.severity === 'critical' ? 'crit' : inc.severity === 'major' ? 'warn' : 'neutral'
              return (
                <div key={i} className="rounded-md border bg-card/50 px-3 py-2">
                  <div className="flex items-center justify-between gap-2">
                    <StatusPill status={tone} label={inc.severity} />
                    <span className="text-[11px] tabular text-muted-foreground">
                      {inc.durationMinutes >= 60
                        ? `${(inc.durationMinutes / 60).toFixed(1)}h`
                        : `${Math.round(inc.durationMinutes)}m`}
                    </span>
                  </div>
                  <div className="mt-1.5 text-[11px] text-muted-foreground tabular">
                    {new Date(inc.startedAt).toLocaleString('en-GB', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}
                    {' → '}
                    {new Date(inc.endedAt).toLocaleString('en-GB', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}
                  </div>
                  <div className="mt-0.5 text-[11px]">
                    ~{fmtCompact(inc.estimatedFailedRequests)} failed requests
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </div>
    </div>
  )
}

// ---- report compare ------------------------------------------------------------

/**
 * A/B drift view for two saved reports. Metric deltas are colored by whether
 * the change is operationally good (availability up, burn/downtime down), not
 * by sign — comparing across services or windows stays readable.
 */
function ReportCompare({ a, b, onClose }: { a: SlaReportPayload; b: SlaReportPayload; onClose: () => void }) {
  const label = (r: SlaReportPayload) =>
    `${r.serviceId} · ${new Date(r.from).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })} → ${new Date(r.to).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })} · SLO ${r.sloTarget}%`

  const rows: {
    key: string
    label: string
    av: string
    bv: string
    delta: number
    goodWhen: 'up' | 'down'
    fmt: (n: number) => string
  }[] = [
    {
      key: 'avail',
      label: 'Availability',
      av: `${a.summary.availabilityPct.toFixed(3)}%`,
      bv: `${b.summary.availabilityPct.toFixed(3)}%`,
      delta: b.summary.availabilityPct - a.summary.availabilityPct,
      goodWhen: 'up',
      fmt: (n) => `${n >= 0 ? '+' : ''}${n.toFixed(3)}pp`,
    },
    {
      key: 'budget',
      label: 'Error budget left',
      av: `${a.summary.errorBudgetPctRemaining.toFixed(1)}%`,
      bv: `${b.summary.errorBudgetPctRemaining.toFixed(1)}%`,
      delta: b.summary.errorBudgetPctRemaining - a.summary.errorBudgetPctRemaining,
      goodWhen: 'up',
      fmt: (n) => `${n >= 0 ? '+' : ''}${n.toFixed(1)}pp`,
    },
    {
      key: 'burn',
      label: 'Burn rate',
      av: `×${a.summary.burnRate.toFixed(2)}`,
      bv: `×${b.summary.burnRate.toFixed(2)}`,
      delta: b.summary.burnRate - a.summary.burnRate,
      goodWhen: 'down',
      fmt: (n) => `${n >= 0 ? '×+' : '×'}${n.toFixed(2)}`,
    },
    {
      key: 'downtime',
      label: 'Downtime',
      av: `${a.summary.totalDowntime.toFixed(1)}m`,
      bv: `${b.summary.totalDowntime.toFixed(1)}m`,
      delta: b.summary.totalDowntime - a.summary.totalDowntime,
      goodWhen: 'down',
      fmt: (n) => `${n >= 0 ? '+' : ''}${n.toFixed(1)}m`,
    },
    {
      key: 'failed',
      label: 'Failed requests',
      av: fmtCompact(a.summary.failedRequests),
      bv: fmtCompact(b.summary.failedRequests),
      delta: b.summary.failedRequests - a.summary.failedRequests,
      goodWhen: 'down',
      fmt: (n) => `${n >= 0 ? '+' : ''}${fmtCompact(Math.abs(n))}${n >= 0 ? '' : ''}`,
    },
    {
      key: 'incidents',
      label: 'Episodes',
      av: String(a.incidents.length),
      bv: String(b.incidents.length),
      delta: b.incidents.length - a.incidents.length,
      goodWhen: 'down',
      fmt: (n) => `${n >= 0 ? '+' : ''}${Math.round(n)}`,
    },
  ]

  // Day-aligned availability deltas (dates present in both windows).
  const bByDate = new Map(b.daily.map((d) => [d.date, d]))
  const dayDeltas = a.daily
    .filter((d) => bByDate.has(d.date))
    .map((d) => ({ date: d.date, delta: bByDate.get(d.date)!.uptimePct - d.uptimePct }))
  const maxAbsDay = Math.max(0.05, ...dayDeltas.map((d) => Math.abs(d.delta)))

  return (
    <div className="rise-in space-y-4">
      <div className="card-surface">
        <SectionHeader
          title="Report comparison"
          hint="drift computed locally from the two saved reports"
          right={
            <button
              onClick={onClose}
              className="flex h-7 items-center gap-1 rounded-md border px-2 text-[11px] text-muted-foreground transition-colors hover:border-ring hover:text-foreground"
            >
              <X className="h-3 w-3" /> close
            </button>
          }
        />
        <div className="flex flex-wrap items-center gap-2 px-4 pb-3 text-[11px]">
          <span className="rounded-full bg-primary/15 px-2.5 py-1 font-mono font-semibold text-primary">A · {label(a)}</span>
          <GitCompareArrows className="h-3.5 w-3.5 text-muted-foreground" />
          <span className="rounded-full border border-primary/40 px-2.5 py-1 font-mono font-semibold text-primary">B · {label(b)}</span>
        </div>

        <div className="grid grid-cols-2 gap-3 px-4 pb-4 lg:grid-cols-6">
          {rows.map((row) => {
            const improved = row.goodWhen === 'up' ? row.delta > 0 : row.delta < 0
            const flat = Math.abs(row.delta) < 1e-9
            const color = flat ? 'var(--muted-foreground)' : improved ? 'var(--ok)' : 'var(--crit)'
            const Arrow = row.delta >= 0 ? ArrowUpRight : ArrowDownRight
            return (
              <div
                key={row.key}
                className="rounded-lg border bg-card/40 p-3 transition-all duration-200 hover:-translate-y-0.5 hover:border-ring/40"
              >
                <div className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground">{row.label}</div>
                <div className="mt-1.5 flex items-baseline gap-1.5 text-[13px] tabular">
                  <span className="text-foreground/70">{row.av}</span>
                  <Arrow className="h-3 w-3 shrink-0" style={{ color }} />
                  <span className="font-semibold" style={{ color: flat ? undefined : color }}>{row.bv}</span>
                </div>
                <div className="mt-1 text-[10px] font-medium tabular" style={{ color }}>
                  {flat ? 'no change' : row.fmt(row.delta)}
                </div>
              </div>
            )
          })}
        </div>

        {dayDeltas.length > 0 && (
          <div className="border-t border-border/50 px-4 py-3">
            <div className="mb-2 flex items-baseline justify-between text-[11px]">
              <span className="font-medium">Daily availability drift</span>
              <span className="text-[10px] text-muted-foreground">
                {dayDeltas.length} shared days · bar = B − A · green = B better
              </span>
            </div>
            <div className="scroll-thin max-h-40 space-y-[3px] overflow-y-auto pr-1">
              {dayDeltas.map((d) => {
                const w = (Math.abs(d.delta) / maxAbsDay) * 50
                const good = d.delta > 0
                const flatDay = d.delta === 0
                return (
                  <div key={d.date} className="group flex items-center gap-2 text-[10px] tabular" title={`${d.date}: ${d.delta >= 0 ? '+' : ''}${d.delta.toFixed(3)}pp`}>
                    <span className="w-20 shrink-0 text-muted-foreground">{d.date.slice(5)}</span>
                    <div className="relative h-2 flex-1">
                      <div className="absolute inset-y-0 left-1/2 w-px bg-border" />
                      {flatDay ? (
                        <div className="absolute inset-y-0 left-1/2 h-2 w-2 -translate-x-1/2 rounded-full bg-muted-foreground/30" />
                      ) : good ? (
                        <div
                          className="absolute inset-y-0 left-1/2 rounded-r-sm transition-all group-hover:opacity-100"
                          style={{ width: `${w}%`, background: 'var(--ok)', opacity: 0.85 }}
                        />
                      ) : (
                        <div
                          className="absolute inset-y-0 rounded-l-sm transition-all group-hover:opacity-100"
                          style={{ right: '50%', width: `${w}%`, background: 'var(--crit)', opacity: 0.85 }}
                        />
                      )}
                    </div>
                    <span
                      className="w-16 shrink-0 text-right font-medium"
                      style={{ color: flatDay ? 'var(--muted-foreground)' : good ? 'var(--ok)' : 'var(--crit)' }}
                    >
                      {d.delta >= 0 ? '+' : ''}{d.delta.toFixed(3)}
                    </span>
                  </div>
                )
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

// ---- small pieces --------------------------------------------------------------

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="flex flex-col gap-1">
      <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
        {label}
      </span>
      {children}
    </label>
  )
}

function MetricTile({
  icon, label, value, sub, color,
}: {
  icon: React.ReactNode
  label: string
  value: string
  sub: string
  color: string
}) {
  return (
    <div className="card-surface group relative overflow-hidden p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-ring/40 hover:shadow-lg hover:shadow-black/20">
      <div className="flex items-center justify-between">
        <span className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">{label}</span>
        <span style={{ color }}>{icon}</span>
      </div>
      <div className="mt-1.5 text-[22px] font-semibold leading-none tracking-tight tabular" style={{ color }}>
        {value}
      </div>
      <div className="mt-1 text-[11px] text-muted-foreground">{sub}</div>
    </div>
  )
}

function LegendDot({ color, label }: { color: string; label: string }) {
  return (
    <span className="flex items-center gap-1.5">
      <span className="h-1.5 w-1.5 rounded-full" style={{ background: color }} />
      {label}
    </span>
  )
}

function ReportSkeleton() {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        {Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="card-surface h-[86px]" />)}
      </div>
      <div className="grid gap-4 xl:grid-cols-[1fr_380px]">
        <Skeleton className="card-surface h-64" />
        <Skeleton className="card-surface h-64" />
      </div>
    </div>
  )
}

// ---- helpers --------------------------------------------------------------------

function availColor(pct: number, slo: number): string {
  if (pct >= slo) return 'var(--ok)'
  if (slo - pct > 0.5) return 'var(--crit)'
  return 'var(--warn)'
}

function burnVerdict(burn: number): string {
  if (burn >= 14.4) return 'fast burn — page the on-call'
  if (burn >= 6) return 'major burn — investigate'
  if (burn >= 1) return 'consuming budget'
  return 'budget sustainable'
}

function fmtBudget(days: number, slo: number): string {
  const minutes = days * 24 * 60 * (1 - slo / 100)
  if (minutes >= 60) return `${(minutes / 60).toFixed(1)}h`
  return `${minutes.toFixed(1)}m`
}

function fmtCompact(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`
  return String(Math.round(n))
}
